name: Conventional commits

on:
  pull_request:
  workflow_call:

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate commit messages are conventional
        uses: wagoid/commitlint-github-action@v5.3.0
        with:
          failOnWarnings: true
