name: commitlint
on:
  pull_request:

jobs:
  main:
    name: Validate commit messages
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.0.2
        with:
          failOnWarnings: true
