name: Conventional commits

on:
  pull_request:
  workflow_call:

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Checkout repository for local testing
        if: github.actor == 'nektos/act'
        uses: actions/checkout@v3

      - name: Checkout repository
        if: github.actor != 'nektos/act'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate commit messages are conventional
        uses: wagoid/commitlint-github-action@v5.0.2
        with:
          failOnWarnings: true
