name: Terraform directory
on:
  workflow_call:
    outputs:
      terraform-dir:
        description: The terraform directory to initialise
        value: ${{ jobs.terraform-directory.outputs.terraform-dir }}

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  terraform-directory:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      terraform-dir: ${{ steps.terraform-dir.outputs.TF_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: true # changed-files unable to authenticate if false

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@cbda684547adc8c052d50711417fa61b428a9f88 # v41.1.2

      # - name: List all changed files
      #   env:
      #     ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #   run: |
      #     for file in "$ALL_CHANGED_FILES"; do
      #       echo "$file was changed"
      #     done

      # Find the directory where files have been changed.
      - name: Get terraform directory
        id: get-terraform-dir
        uses: tj-actions/changed-files@cbda684547adc8c052d50711417fa61b428a9f88 # v41.1.2
        # Step fails if nothing found.
        continue-on-error: true # Allows workflow to proceed if no files found
        with:
          files: |
            **/*.tf
            **/*.tfvars
          dir_names: true
          json: true

      - name: List terraform directory
        if: ${{ steps.get-terraform-dir.conclusion == 'success'}}
        run: echo "${{ steps.get-terraform-dir.outputs.all_changed_files }}"

      # This output is used as input for the lint workflow matrix strategy
      # The native output, eg: ["terraform/github","terraform/tfe"] doesn't work
      # Convert the output to one that does: ['terraform/tfe','terraform/github']
      - name: Format Terraform directory output
        id: terraform-dir
        if: ${{ steps.get-terraform-dir.conclusion == 'success'}}
        env:
          GET_TF_DIR: ${{ steps.get-terraform-dir.outputs.all_changed_files }}
        run: |
          TF_DIR_FMT=$(echo "$GET_TF_DIR" | sed s:\":\':g)
          echo "TF_DIR=$TF_DIR_FMT" >> "$GITHUB_OUTPUT"

      - name: Summary if successful
        if: ${{ steps.get-terraform-dir.conclusion == 'success'}}
        env:
          TF_DIR: ${{ steps.terraform-dir.outputs.TF_DIR }}
        run: |
          echo "### Terraform directories found :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $$GITHUB_STEP_SUMMARY
          echo "${{ env.TF_DIR }} >> $GITHUB_STEP_SUMMARY
