name: Lint and test
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Setup Terraform
        if: contains(steps.changed-files.outputs.all_changed_files, '**/*.tf')
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialise Terraform
        if: contains(steps.changed-files.outputs.all_changed_files, '**/*.tf')
        working-directory: ./terraform
        run: terraform init

      - name: Lint with trunk
        if: ${{ always() }}
        uses: trunk-io/trunk-action@v1.0.6
