name: Lint and test
on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialise Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Lint with trunk
        uses: trunk-io/trunk-action@v1.0.4
