name: Lint
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: number

# Declare default permissions as read only.
permissions: read-all

jobs:
  find-terraform:
    uses: ./.github/workflows/get-terraform-dir.yaml
    permissions:
      contents: read

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    needs: [find-terraform]
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false

      - name: Setup Terraform
        if: ${{ needs.find-terraform.outputs.terraform-dir != '' }}
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ inputs.terraform-version }}
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

      # Initialise terraform in the directory where terraform file have changed.
      - name: Initialise Terraform
        if: ${{ needs.find-terraform.outputs.terraform-dir != ''}}
        working-directory: ${{ needs.find-terraform.outputs.terraform-dir }}
        run: terraform init

      - name: Lint with trunk
        if: ${{ always() }} # Run anyway, even if no terraform
        uses: trunk-io/trunk-action@b033203e937f42022e351f1313cf84123c4472df # v1.0.7
