name: Lint
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_call:
    inputs:
      terraform-dir:
        type: string
        required: false
    secrets:
      TFC_API_TOKEN:
        required: false

# Disable permissions for all available scopes
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # not required (see slack) but produces an error in the logs
      # https://trunkcommunity.slack.com/archives/C04GAE5EA5S/p1677846825881319?thread_ts=1676214812.584879&cid=C04GAE5EA5S
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}-${{ inputs.terraform-dir }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: true # lint fails to authenticate when false

      - name: Setup tfswitch
        if: ${{ inputs.terraform-dir != '' }}
        uses: stv-io/action-tfswitch@b6c5e07f48a6de1934acf5e9c67bd3b21423e9e1 # v1.0.0

      - name: Get Terraform Version
        if: ${{ inputs.terraform-dir != '' }}
        run: |
          tfswitch --chdir=${{ inputs.terraform-dir }}
          echo "TERRAFORM_VERSION=$(terraform --version -json | jq -r .terraform_version)" >> "$GITHUB_ENV"

      - name: Setup Terraform
        if: ${{ inputs.terraform-dir != '' }}
        uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3
        with:
          # Using workflow syntax, eg: $TERRAFORM_VERSION does not work
          # env context must be used
          # linting error stating: "context might be invalid" will hopefully be fixed soon
          # https://github.com/github/vscode-github-actions/issues/47
          tofu_version: ${{ env.TERRAFORM_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      # Initialise terraform in the directory where terraform file have changed.
      - name: Initialise Terraform
        if: ${{ inputs.terraform-dir != ''}}
        working-directory: ${{ inputs.terraform-dir }}
        run: tofu init

      - name: Lint with trunk
        if: ${{ always() }} # Run anyway, even if no terraform
        uses: trunk-io/trunk-action@34242ec4eb8cf594887600f1f9b889e7c630ec18 # v1.19.0
