name: Lint
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: number

permissions:
  contents: read
  checks: write

jobs:
  find-terraform:
    uses: ./.github/workflows/get-terraform-dir.yaml

  lint:
    runs-on: ubuntu-latest
    needs: find-terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        if: needs.find-terraform.outputs.terraform-dir != '""'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      #Initialise terraform in the directory where terraform file have changed.
      - name: Initialise Terraform
        if: needs.find-terraform.outputs.terraform-dir != '""'
        working-directory: ${{ needs.find-terraform.outputs.terraform-dir }}
        run: terraform init

      - name: Lint with trunk
        if: ${{ always() }} #Run anyway, even if no terraform
        uses: trunk-io/trunk-action@v1.0.6
