name: Lint and test
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: number

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Search for terraform files
        id: find-terraform
        uses: ./.github/workflows/changed-files-and-dirs.yaml
        with:
          file-type: '.tf'

      - name: Setup Terraform
        if: contains(steps.find-terraform.outputs.changed-files, '.tf')
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform-version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      #Initialise terraform in the directory where terraform file have changed.
      - name: Initialise Terraform
        if: contains(steps.find-terraform.outputs.changed-files, '.tf')
        working-directory: ${{ steps.find-terraform.outputs.dir-names }}
        run: terraform init

      - name: Lint with trunk
        if: ${{ always() }}
        uses: trunk-io/trunk-action@v1.0.6
