name: Semantic PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pr-title:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request title is conventional
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
