name: Semantic Release

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get GitHub authentication token
        if: ${{ ! env.ACT }}
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: 3ware

      - name: Create GitHub release and update CHANGELOG
        if: ${{ ! env.ACT }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - name: Local test release
        if: ${{ env.ACT }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
