name: Semantic Release

on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [main]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  get-temp-token:
    uses: ./.github/workflows/get-workflow-token.yaml
    secrets: inherit

  semantic-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: [get-temp-token]
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          persist-credentials: false

      - name: Decrypt the installation access token
        id: decrypt-token
        run: |
          DECRYPTED_TOKEN=$(gpg --decrypt --quiet --batch --passphrase "$KEY" \
          --output - <(echo "${{ needs.get-temp-token.outputs.temp-token }}" \
          | base64 --decode))
          echo "::add-mask::$DECRYPTED_TOKEN"
          echo "temp-token=$DECRYPTED_TOKEN" >> $GITHUB_OUTPUT
        env:
          KEY: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}

      - name: Create GitHub release and update CHANGELOG
        if: ${{ ! env.ACT }}
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # v3.2.0
        with:
          semantic_version: 19.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ steps.decrypt-token.outputs.temp-token }}

      - name: Local test release
        if: ${{ env.ACT }}
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # v3.2.0
        with:
          semantic_version: 19.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
