name: Terraform docs
on:
  workflow_call:
    inputs:
      terraform-dir:
        type: string
        required: true

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.terraform-dir }}
      cancel-in-progress: true
    env:
      WORKING_DIR: ${{ inputs.terraform-dir }}
      TF_DOCS_FILE: README.md

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: true # terraform-docs unable to authenticate if false

      - name: Render terraform docs
        id: terraform-docs
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          working-dir: ${{ inputs.terraform-dir }}
          output-file: ${{ env.TF_DOCS_FILE }}
          output-method: inject

      - name: Set environment variables
        if: ${{ steps.terraform-docs.outputs.num_changed != 0 }}
        run: |
          echo "Number of files changed = ${{ steps.terraform-docs.outputs.num_changed }}"
          echo "FILE_TO_COMMIT=${{ env.WORKING_DIR }}/${{ env.TF_DOCS_FILE }}" >> "$GITHUB_ENV"
          echo "COMMIT_SCOPE=$(awk -F"/" '{print $NF}' <<< ${{ inputs.terraform-dir }})" >> "$GITHUB_ENV"
          echo "PR_NUMBER=${{ github.event.pull_request_review.pull_request.number }}" >> "$GITHUB_ENV"

      - name: Push verified commit
        if: ${{ steps.terraform-docs.outputs.num_changed != 0 }}
        id: push-with-sig
        uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "docs(${{ env.COMMIT_SCOPE }}): Update ${{ env.TF_DOCS_FILE }} [skip ci]"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: ${{ env.FILE_TO_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary with commit failure
        if: ${{ failure() && steps.push-with-sig.outcome == 'failure' }}
        run: |
          echo "# :bangbang: ${{ env.TF_DOCS_FILE }} not updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Commit failure" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Terraform documentation has not been updated" >> $GITHUB_STEP_SUMMARY
          echo "Please review the logs" >> $GITHUB_STEP_SUMMARY

      - name: Summary with document changes
        if: ${{ steps.push-with-sig.conclusion == 'success' }}
        env:
          BRANCH: ${{ github.head_ref  }}
        run: |
          echo "# :white_check_mark: Terraform docs updated $FILE_PATH" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$TF_DOCS_FILE updated for $COMMIT_SCOPE module on $BRANCH" via pull request: >> $GITHUB_STEP_SUMMARY
          echo "[#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Summary without document changes
        if: ${{ steps.terraform-docs.outputs.num_changed != 0 }}
        run: |
          echo "# :negative_squared_cross_mark: ${{ env.TF_DOCS_FILE }} not updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Terraform changes were not detected on this workflow run" >> $GITHUB_STEP_SUMMARY
