name: Generate terraform docs
on:
  workflow_call:

jobs:
  find-terraform:
    uses: ./.github/workflows/get-terraform-dir.yaml

  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: find-terraform
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ needs.find-terraform.outputs.terraform-dir }}
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "update terraform documentation"
          # See this link for configuring an apps email and username:
          # https://github.com/orgs/community/discussions/24664
          git-push-user-name: "3ware-release[bot]"
          # GitHub App user ID from:
          # https://api.github.com/users/3ware-release%5Bbot%5D
          git-push-user-email: "108564841+3ware-release[bot]@users.noreply.github.com"
