name: tfsec Code Analysis

on:
  workflow_call:
    inputs:
      tfsec_args:
        description: "Command line arguments to pass to tfsec."
        default: ""
        required: false
        type: string

jobs:
  find-terraform:
    permissions:
      contents: read
    uses: ./.github/workflows/get-terraform-dir.yaml

  tfsec-pr-commenter:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: find-terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add tfsec comments to pull request
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ${{ needs.find-terraform.outputs.terraform-dir }}
          tfsec_args: ${{ inputs.tfsec_args }}
