name: tfsec Code Analysis

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'The directory to scan terraform file in.'
        default: '.'
        required: true
        type: string
      tfsec_args:
        description: 'Command line arguments to pass to tfsec.'
        default: ''
        required: false
        type: string

jobs:
  tfsec-pr-commenter:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add tfsec comments to pull request
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
