name: Trunk Check
on: pull_request

jobs:
  main:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Linters/Formatters
        uses: actions/cache@v3
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Initialise Terraform
        working-directory: ./terraform
        run: terraform init
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.3
