name: summary

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-all-checks:
    permissions:
      checks: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
